apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-explainer-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      project: document-explainer
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        project: document-explainer
    spec:
      containers:
      - name: document-explainer-pod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        image: fil404/document_explainer:main
