apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-explainer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      project: document-explainer
  template:
    metadata:
      labels:
        project: document-explainer
    spec:
      containers:
      - name: document-explainer-pod
        ports:
        - containerPort: 8000
        image: fil404/document_explainer:main
