version: '3.9'

services:
    app:
        build:
            context: .
            network: host
            dockerfile: Dockerfile
        image: document-explainer-image
        container_name: document_explainer
        ports:
            - 8080:8080
        volumes:
            - .:/app
        env_file:
          - .env
        command: streamlit run ./src/app.py --server.port 8080
